##begin config
basename Bluetooth
libbase BluetoothBase
libbasetype struct BluetoothBase
version 1.0
##end config

##begin cdef
#include <exec/types.h>

#define BT_API_VERSION 1
##end cdef

##begin cdefprivate
#include "bluetooth_intern.h"
##end cdefprivate

##begin functionlist
ULONG BT_GetAPIVersion() ()
##end functionlist
